import { type ReactElement, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { CalendarDays, Globe, Loader2, Newspaper, Save, Users, X } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import type { SalesDeskErpNewsItemDto } from '../../api/salesdesk-api';
import type { ErpNewsMetaOverlay } from '../../lib/erp-news-types';
import { ERP_NEWS_MODULE_LABELS } from '../../lib/erp-news-types';
import {
  SD_CREATE_ACTION_BAR_CLASSNAME,
  SD_CREATE_FORM_INPUT_CLASSNAME,
  SD_CREATE_FORM_LABEL_CLASSNAME,
  SD_CREATE_HEADER_FORM_SURFACE_CLASSNAME,
  SD_CREATE_PAGE_CONTAINER_CLASSNAME,
} from '../../lib/salesdesk-document-create-styles';
import {
  SD_DOCUMENT_BUTTON_BASE,
  SD_DOCUMENT_BUTTON_SAVE,
} from '../../lib/salesdesk-document-button-styles';
import { SD_SELECT_CONTENT } from '../../lib/salesdesk-popup-styles';
import type { SalesDeskGroupDto } from '../../types/salesdesk-group-types';
import {
  createDefaultErpNewsFormValues,
  erpNewsFormSchema,
  toErpNewsFormValues,
  type ErpNewsFormValues,
} from '../../types/salesdesk-schemas';
import { SalesDeskVisitFormSection } from '../visit-forms/SalesDeskVisitFormSection';
import { SalesDeskErpNewsGroupSelect } from './SalesDeskErpNewsGroupSelect';

interface SalesDeskErpNewsEditorProps {
  entity?: SalesDeskErpNewsItemDto | null;
  overlay?: ErpNewsMetaOverlay | null;
  groups?: SalesDeskGroupDto[];
  isSaving?: boolean;
  onSubmit: (values: ErpNewsFormValues) => Promise<void>;
  onCancel: () => void;
}

export function SalesDeskErpNewsEditor({
  entity,
  overlay,
  groups = [],
  isSaving = false,
  onSubmit,
  onCancel,
}: SalesDeskErpNewsEditorProps): ReactElement {
  const isEditMode = entity != null;
  const isSystemNews = overlay?.isAutoGenerated === true || overlay?.sourceType === 'system';

  const form = useForm<ErpNewsFormValues>({
    resolver: zodResolver(erpNewsFormSchema),
    mode: 'onChange',
    defaultValues: entity
      ? toErpNewsFormValues(entity, overlay)
      : createDefaultErpNewsFormValues(),
  });

  useEffect(() => {
    form.reset(entity ? toErpNewsFormValues(entity, overlay) : createDefaultErpNewsFormValues());
  }, [entity, overlay, form]);

  const submit = form.handleSubmit(
    async (values) => {
      try {
        await onSubmit(values);
      } catch (error) {
        toast.error(error instanceof Error ? error.message : 'Haber kaydedilemedi.');
      }
    },
    (errors) => {
      const firstError = Object.values(errors).find(
        (fieldError) => fieldError && typeof (fieldError as { message?: unknown }).message === 'string'
      ) as { message?: string } | undefined;
      toast.error(firstError?.message || 'Lutfen zorunlu alanlari kontrol edin.');
    }
  );

  return (
    <Form {...form}>
      <form onSubmit={submit} className={SD_CREATE_PAGE_CONTAINER_CLASSNAME}>
        <div>
          <h1 className="text-2xl font-semibold text-slate-900 dark:text-slate-50">
            {isSystemNews ? 'Sistem Haberi' : isEditMode ? 'Haberi Duzenle' : 'Yeni ERP Haberi'}
          </h1>
          <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
            {isSystemNews
              ? 'Bu kayit modul tetikleyicileri tarafindan olusturuldu; yalnizca okuma durumu guncellenebilir.'
              : 'Manuel veya dis kaynak haberlerini hedef gruplara yonlendirerek kaydedin'}
          </p>
        </div>

        <div className={`mt-6 space-y-6 ${SD_CREATE_HEADER_FORM_SURFACE_CLASSNAME}`}>
          <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
            <SalesDeskVisitFormSection icon={Newspaper} title="Haber Ozeti" subtitle="Modul, baslik ve kaynak">
              <div className="grid grid-cols-1 gap-4">
                <FormField
                  control={form.control}
                  name="module"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Modul *</FormLabel>
                      <Select value={field.value} onValueChange={field.onChange} disabled={isSystemNews}>
                        <FormControl>
                          <SelectTrigger className={SD_CREATE_FORM_INPUT_CLASSNAME}>
                            <SelectValue placeholder="Modul secin" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent className={SD_SELECT_CONTENT}>
                          {Object.entries(ERP_NEWS_MODULE_LABELS).map(([value, label]) => (
                            <SelectItem key={value} value={value}>
                              {label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="title"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Baslik *</FormLabel>
                      <FormControl>
                        <textarea
                          {...field}
                          rows={3}
                          disabled={isSystemNews}
                          placeholder="Haber basligi"
                          className="w-full rounded-xl border border-[var(--crm-app-border)] bg-[var(--crm-app-input)] px-4 py-3 text-sm text-slate-900 shadow-sm outline-none focus-visible:border-[var(--crm-brand-accent)] focus-visible:ring-[3px] focus-visible:ring-[var(--crm-brand-focus-glow)] disabled:opacity-60 dark:text-slate-100"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <FormField
                    control={form.control}
                    name="sourceType"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Kaynak tipi</FormLabel>
                        <Select value={field.value} onValueChange={field.onChange} disabled={isSystemNews}>
                          <FormControl>
                            <SelectTrigger className={SD_CREATE_FORM_INPUT_CLASSNAME}>
                              <SelectValue />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent className={SD_SELECT_CONTENT}>
                            <SelectItem value="manual">Manuel</SelectItem>
                            <SelectItem value="external">Dis kaynak</SelectItem>
                          </SelectContent>
                        </Select>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="score"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Puan (0-10)</FormLabel>
                        <FormControl>
                          <Input
                            {...field}
                            type="number"
                            min={0}
                            max={10}
                            disabled={isSystemNews}
                            className={SD_CREATE_FORM_INPUT_CLASSNAME}
                            onChange={(event) => field.onChange(Number(event.target.value))}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <FormField
                  control={form.control}
                  name="source"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Kaynak etiketi</FormLabel>
                      <FormControl>
                        <Input {...field} disabled={isSystemNews} placeholder="Orn. Resmi Gazete" className={SD_CREATE_FORM_INPUT_CLASSNAME} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </SalesDeskVisitFormSection>

            <SalesDeskVisitFormSection
              icon={Globe}
              title="Yayin ve Hedefleme"
              subtitle="Tarih, URL, gruplar ve okuma"
              badgeClassName="bg-violet-500/10 text-violet-600 ring-1 ring-violet-400/25 dark:text-violet-300"
            >
              <div className="grid grid-cols-1 gap-4">
                <FormField
                  control={form.control}
                  name="sourceUrl"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Kaynak URL</FormLabel>
                      <FormControl>
                        <Input {...field} disabled={isSystemNews} placeholder="https://..." className={SD_CREATE_FORM_INPUT_CLASSNAME} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="publishedAt"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Yayin Tarihi *</FormLabel>
                      <FormControl>
                        <Input {...field} type="date" disabled={isSystemNews} className={SD_CREATE_FORM_INPUT_CLASSNAME} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="targetGroupIds"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>
                        <Users size={14} className="mr-1 inline" />
                        Hedef gruplar
                      </FormLabel>
                      <SalesDeskErpNewsGroupSelect
                        groups={groups}
                        value={field.value}
                        onChange={field.onChange}
                        disabled={isSystemNews}
                      />
                    </FormItem>
                  )}
                />

                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  <FormField
                    control={form.control}
                    name="isCritical"
                    render={({ field }) => (
                      <FormItem className="flex items-center gap-3 rounded-xl border border-[var(--crm-app-border)] bg-[var(--crm-app-panel-muted)]/60 px-4 py-3">
                        <FormControl>
                          <Checkbox checked={field.value} onCheckedChange={field.onChange} disabled={isSystemNews} />
                        </FormControl>
                        <div>
                          <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Kritik haber</FormLabel>
                        </div>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="isRead"
                    render={({ field }) => (
                      <FormItem className="flex items-center gap-3 rounded-xl border border-[var(--crm-app-border)] bg-[var(--crm-app-panel-muted)]/60 px-4 py-3">
                        <FormControl>
                          <Checkbox checked={field.value} onCheckedChange={field.onChange} />
                        </FormControl>
                        <div>
                          <FormLabel className={SD_CREATE_FORM_LABEL_CLASSNAME}>Okundu</FormLabel>
                        </div>
                      </FormItem>
                    )}
                  />
                </div>
              </div>
            </SalesDeskVisitFormSection>
          </div>

          <SalesDeskVisitFormSection
            icon={CalendarDays}
            title="Puan Rehberi"
            subtitle="Haber onceligini hizli degerlendirin"
            badgeClassName="bg-sky-500/10 text-sky-600 ring-1 ring-sky-400/25 dark:text-sky-300"
          >
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
              <div className="rounded-xl border border-[var(--crm-app-border)] bg-[var(--crm-app-panel-muted)]/60 px-4 py-3 text-sm">
                <p className="font-semibold text-emerald-600 dark:text-emerald-300">8-10 Yuksek</p>
                <p className="mt-1 text-xs text-[var(--crm-app-text-muted)]">Satis ve operasyonu dogrudan etkiler</p>
              </div>
              <div className="rounded-xl border border-[var(--crm-app-border)] bg-[var(--crm-app-panel-muted)]/60 px-4 py-3 text-sm">
                <p className="font-semibold text-amber-600 dark:text-amber-300">5-7 Orta</p>
                <p className="mt-1 text-xs text-[var(--crm-app-text-muted)]">Takip edilmeli, acil degil</p>
              </div>
              <div className="rounded-xl border border-[var(--crm-app-border)] bg-[var(--crm-app-panel-muted)]/60 px-4 py-3 text-sm">
                <p className="font-semibold text-slate-600 dark:text-slate-300">0-4 Dusuk</p>
                <p className="mt-1 text-xs text-[var(--crm-app-text-muted)]">Bilgi amacli, dusuk oncelik</p>
              </div>
            </div>
          </SalesDeskVisitFormSection>
        </div>

        <div className={SD_CREATE_ACTION_BAR_CLASSNAME}>
          <Button type="button" variant="outline" onClick={onCancel} className={SD_DOCUMENT_BUTTON_BASE}>
            <X size={16} />
            Iptal
          </Button>
          <Button type="submit" disabled={isSaving || form.formState.isSubmitting} className={SD_DOCUMENT_BUTTON_SAVE}>
            {isSaving || form.formState.isSubmitting ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                Kaydediliyor...
              </>
            ) : (
              <>
                <Save size={16} />
                {isEditMode ? 'Guncelle' : 'Kaydet'}
              </>
            )}
          </Button>
        </div>
      </form>
    </Form>
  );
}
