import type { SalesDeskErpNewsItemDto } from '../api/salesdesk-api';
import type {
  ErpNewsMetaOverlay,
  ErpNewsModule,
  ErpNewsReferenceType,
  ErpNewsSourceType,
  SalesDeskErpNewsItemEnriched,
} from './erp-news-types';

const MODULE_ALIASES: Record<string, ErpNewsModule> = {
  DEPO: 'DEPO',
  DEPo: 'DEPO',
  WAREHOUSE: 'DEPO',
  CRM: 'CRM',
  SATIS: 'CRM',
  URETIM: 'URETIM',
  PRODUCTION: 'URETIM',
  IK: 'IK',
  HR: 'IK',
  GIB: 'GIB',
  NETSIS: 'NETSIS',
  ERP: 'ERP',
};

function normalizeModule(topic?: string | null): ErpNewsModule {
  const key = (topic ?? '').trim().toUpperCase();
  return MODULE_ALIASES[key] ?? (key ? 'OTHER' : 'ERP');
}

function inferSourceType(
  item: SalesDeskErpNewsItemDto,
  overlay?: ErpNewsMetaOverlay | null
): ErpNewsSourceType {
  if (overlay?.sourceType) return overlay.sourceType;
  if (item.source?.toLowerCase().includes('otomatik')) return 'system';
  if (item.sourceUrl?.trim()) return 'external';
  return 'manual';
}

function inferAutoGenerated(sourceType: ErpNewsSourceType, overlay?: ErpNewsMetaOverlay | null): boolean {
  if (overlay?.isAutoGenerated != null) return overlay.isAutoGenerated;
  return sourceType === 'system';
}

export function normalizeErpNewsItem(
  item: SalesDeskErpNewsItemDto,
  overlay?: ErpNewsMetaOverlay | null
): SalesDeskErpNewsItemEnriched {
  const module = overlay?.module ?? normalizeModule(item.topic);
  const sourceType = inferSourceType(item, overlay);

  return {
    ...item,
    sourceType,
    module,
    targetGroupIds: overlay?.targetGroupIds ?? [],
    targetGroupNames: overlay?.targetGroupNames ?? [],
    referenceType: overlay?.referenceType ?? 'None',
    referenceId: overlay?.referenceId ?? null,
    isAutoGenerated: inferAutoGenerated(sourceType, overlay),
    triggerKey: overlay?.triggerKey ?? null,
  };
}

export function enrichErpNewsItems(
  items: SalesDeskErpNewsItemDto[],
  overlays: Record<string, ErpNewsMetaOverlay>
): SalesDeskErpNewsItemEnriched[] {
  return items.map((item) => normalizeErpNewsItem(item, overlays[String(item.id)] ?? null));
}

export function moduleToTopic(module: ErpNewsModule): string {
  return module;
}

export function defaultSourceLabel(sourceType: ErpNewsSourceType, module: ErpNewsModule): string {
  if (sourceType === 'system') return `Otomatik · ${module}`;
  if (sourceType === 'external') return 'Dis kaynak';
  return 'Manuel kayit';
}

export function isReferenceType(value: string): value is ErpNewsReferenceType {
  return [
    'None',
    'Product',
    'PotentialCustomer',
    'Task',
    'Visit',
    'Quote',
    'Employee',
    'ExternalFeed',
    'HangfireJob',
  ].includes(value);
}
