import type { SalesDeskGroupDto } from '../types/salesdesk-group-types';
import type { ErpNewsFormValues } from '../types/salesdesk-schemas';
import type { ErpNewsMetaOverlay } from './erp-news-types';
import { defaultSourceLabel } from './erp-news-normalize';

export function buildOverlayFromFormValues(
  values: ErpNewsFormValues,
  groups: SalesDeskGroupDto[],
  options?: { isAutoGenerated?: boolean; referenceType?: ErpNewsMetaOverlay['referenceType']; referenceId?: string | null; triggerKey?: string | null }
): Omit<ErpNewsMetaOverlay, 'newsId' | 'updatedAt'> {
  const targetGroupNames = groups.filter((group) => values.targetGroupIds.includes(group.id)).map((group) => group.name);
  const sourceType = options?.isAutoGenerated ? 'system' : values.sourceType;

  return {
    sourceType,
    module: values.module,
    targetGroupIds: values.targetGroupIds,
    targetGroupNames,
    referenceType: options?.referenceType ?? 'None',
    referenceId: options?.referenceId ?? null,
    isAutoGenerated: options?.isAutoGenerated ?? false,
    triggerKey: options?.triggerKey ?? null,
  };
}

export function buildManualSourceLabel(values: ErpNewsFormValues): string | undefined {
  if (values.source?.trim()) return values.source.trim();
  return defaultSourceLabel(values.sourceType, values.module);
}
