export type ErpNewsSourceType = 'manual' | 'system' | 'external';

export type ErpNewsModule =
  | 'DEPO'
  | 'CRM'
  | 'URETIM'
  | 'IK'
  | 'GIB'
  | 'NETSIS'
  | 'ERP'
  | 'OTHER';

export type ErpNewsReferenceType =
  | 'None'
  | 'Product'
  | 'PotentialCustomer'
  | 'Task'
  | 'Visit'
  | 'Quote'
  | 'Employee'
  | 'ExternalFeed'
  | 'HangfireJob';

export interface ErpNewsMetaOverlay {
  newsId: number;
  sourceType: ErpNewsSourceType;
  module: ErpNewsModule;
  targetGroupIds: number[];
  targetGroupNames?: string[];
  referenceType: ErpNewsReferenceType;
  referenceId?: string | null;
  isAutoGenerated: boolean;
  triggerKey?: string | null;
  updatedAt?: string;
}

export interface SalesDeskErpNewsItemEnriched {
  id: number;
  topic: string;
  title: string;
  source?: string | null;
  sourceUrl?: string | null;
  score: number;
  isCritical: boolean;
  isRead: boolean;
  publishedAt: string;
  sourceType: ErpNewsSourceType;
  module: ErpNewsModule;
  targetGroupIds: number[];
  targetGroupNames: string[];
  referenceType: ErpNewsReferenceType;
  referenceId?: string | null;
  isAutoGenerated: boolean;
  triggerKey?: string | null;
}

export const ERP_NEWS_SOURCE_TYPE_LABELS: Record<ErpNewsSourceType, string> = {
  manual: 'Manuel',
  system: 'Sistem',
  external: 'Dis Kaynak',
};

export const ERP_NEWS_MODULE_LABELS: Record<ErpNewsModule, string> = {
  DEPO: 'Depo',
  CRM: 'CRM / Satis',
  URETIM: 'Uretim',
  IK: 'Insan Kaynaklari',
  GIB: 'GIB',
  NETSIS: 'Netsis',
  ERP: 'ERP',
  OTHER: 'Diger',
};

export const ERP_NEWS_REFERENCE_TYPE_LABELS: Record<ErpNewsReferenceType, string> = {
  None: 'Yok',
  Product: 'Urun / Stok',
  PotentialCustomer: 'Potansiyel Cari',
  Task: 'Gorev',
  Visit: 'Ziyaret',
  Quote: 'Teklif',
  Employee: 'Calisan',
  ExternalFeed: 'Dis Feed',
  HangfireJob: 'Arka Plan Isi',
};

export type ErpNewsFeedFilter =
  | 'all'
  | 'system'
  | 'manual'
  | 'external'
  | 'unread'
  | 'critical'
  | 'today'
  | 'my-feed';

export function buildErpNewsTriggerKey(
  module: ErpNewsModule,
  referenceType: ErpNewsReferenceType,
  referenceId: string
): string {
  return `${module}:${referenceType}:${referenceId}`;
}
