import { type ReactElement } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { SalesDeskErpNewsEditor } from '../erp-news/SalesDeskErpNewsEditor';
import {
  useCreateSalesDeskErpNews,
  useSalesDeskErpNews,
  useUpdateSalesDeskErpNews,
} from '../../hooks/useSalesDeskModules';
import { useSalesDeskGroupList } from '../../hooks/useSalesDeskGroups';
import { useErpNewsMetaBundle, useSaveErpNewsMetaOverlay } from '../../hooks/useErpNewsMeta';
import { buildManualSourceLabel, buildOverlayFromFormValues } from '../../lib/erp-news-meta-mapper';
import type { ErpNewsFormValues } from '../../types/salesdesk-schemas';
import { toErpNewsFormValues, toErpNewsPayload } from '../../types/salesdesk-schemas';
import { salesDeskPageShellClass } from '../../lib/salesdesk-shared';
import { salesDeskApi } from '../../api/salesdesk-api';

export function SalesDeskErpNewsCreatePage(): ReactElement {
  const navigate = useNavigate();
  const createNews = useCreateSalesDeskErpNews();
  const saveOverlay = useSaveErpNewsMetaOverlay();
  const { data: groups = [] } = useSalesDeskGroupList();

  const handleSubmit = async (values: ErpNewsFormValues): Promise<void> => {
    const created = await createNews.mutateAsync(values);
    const payload = {
      ...toErpNewsPayload(values),
      source: buildManualSourceLabel(values),
    };
    await salesDeskApi.erpNews.update(created.id, payload).catch(() => undefined);
    await saveOverlay.mutateAsync({
      newsId: created.id,
      overlay: buildOverlayFromFormValues(values, groups),
    });
    navigate('/salesdesk/erp-news');
  };

  return (
    <div className={salesDeskPageShellClass}>
      <button
        type="button"
        onClick={() => navigate('/salesdesk/erp-news')}
        className="mb-4 inline-flex items-center gap-2 text-sm font-medium text-[var(--crm-brand-accent)] transition-colors hover:text-[var(--crm-brand-primary)]"
      >
        <ArrowLeft size={16} />
        Haber listesine don
      </button>

      <SalesDeskErpNewsEditor
        groups={groups}
        isSaving={createNews.isPending || saveOverlay.isPending}
        onSubmit={handleSubmit}
        onCancel={() => navigate('/salesdesk/erp-news')}
      />
    </div>
  );
}

export function SalesDeskErpNewsEditPage(): ReactElement {
  const navigate = useNavigate();
  const params = useParams();
  const newsId = Number(params.id);
  const updateNews = useUpdateSalesDeskErpNews();
  const saveOverlay = useSaveErpNewsMetaOverlay();
  const { data: groups = [] } = useSalesDeskGroupList();
  const { data: entity, isPending, isError, error } = useSalesDeskErpNews(Number.isFinite(newsId) ? newsId : null);
  const { data: metaBundle } = useErpNewsMetaBundle();
  const overlay = entity ? metaBundle?.overlays[String(entity.id)] ?? null : null;
  const isSystemNews = overlay?.isAutoGenerated === true || overlay?.sourceType === 'system';

  const handleSubmit = async (values: ErpNewsFormValues): Promise<void> => {
    if (!entity) return;

    if (isSystemNews) {
      await updateNews.mutateAsync({
        id: entity.id,
        values: { ...toErpNewsFormValues(entity, overlay), isRead: values.isRead },
      });
    } else {
      await updateNews.mutateAsync({ id: entity.id, values });
      const payload = {
        ...toErpNewsPayload(values),
        source: buildManualSourceLabel(values),
      };
      await salesDeskApi.erpNews.update(entity.id, payload).catch(() => undefined);
      await saveOverlay.mutateAsync({
        newsId: entity.id,
        overlay: buildOverlayFromFormValues(values, groups),
      });
    }

    navigate('/salesdesk/erp-news');
  };

  if (!Number.isFinite(newsId) || newsId <= 0) {
    return (
      <div className={salesDeskPageShellClass}>
        <p className="text-sm text-rose-500">Gecersiz haber kaydi.</p>
      </div>
    );
  }

  if (isPending) {
    return (
      <div className={`${salesDeskPageShellClass} flex min-h-[320px] items-center justify-center gap-2 text-sm text-[var(--crm-app-text-muted)]`}>
        <Loader2 size={18} className="animate-spin" />
        Haber yukleniyor...
      </div>
    );
  }

  if (isError || !entity) {
    return (
      <div className={salesDeskPageShellClass}>
        <p className="text-sm text-rose-500">{(error as Error)?.message || 'Haber bulunamadi.'}</p>
      </div>
    );
  }

  return (
    <div className={salesDeskPageShellClass}>
      <button
        type="button"
        onClick={() => navigate('/salesdesk/erp-news')}
        className="mb-4 inline-flex items-center gap-2 text-sm font-medium text-[var(--crm-brand-accent)] transition-colors hover:text-[var(--crm-brand-primary)]"
      >
        <ArrowLeft size={16} />
        Haber listesine don
      </button>

      <SalesDeskErpNewsEditor
        entity={entity}
        overlay={overlay}
        groups={groups}
        isSaving={updateNews.isPending || saveOverlay.isPending}
        onSubmit={handleSubmit}
        onCancel={() => navigate('/salesdesk/erp-news')}
      />
    </div>
  );
}
